version: '2'
services:
  taskmanagementsoftware_server-app:
    image: taskmanagementsoftware_server
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATASOURCE_URL=jdbc:postgresql://taskmanagementsoftware_server-postgresql:5432/TaskManagementSoftware_server
      - JHIPSTER_SLEEP=30 # gives time for other services to boot before the application
    ports:
      - 8080:8080
  taskmanagementsoftware_server-postgresql:
    extends:
      file: postgresql.yml
      service: taskmanagementsoftware_server-postgresql
